resolver: lts-13.7
packages:
- '.'
nix:
  enable: false
  packages: [gmp]
extra-deps:
- git: https://github.com/bkase/kademlia.git
  commit: e6fd924c36701fb338702a929f70f06c24f2e7e2
flags: {}
extra-package-dbs: []
