resolver: lts-13.7
compiler: ghc-8.6.4
packages:
- '.'
nix:
  enable: false
  packages: [gmp]
extra-deps:
- git: https://github.com/CodaProtocol/kademlia.git
  commit: ea9ff68b03e66541e4be77f8e2561352360cafcd
flags: {}
extra-package-dbs: []
