apiVersion: v2
name: snark-worker
description: A Helm chart for Mina Protocol's SNARK worker nodes
type: application
version: 0.1.7
appVersion: 1.16.0
dependencies:
icon: https://github.com/MinaProtocol/mina/blob/develop/frontend/website/public/static/img/coda-logo@3x.png
keywords:
- snarks
- zero-knowledge
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/develop/src/lib/snark_worker
