pull_request_rules:
    - name: automatically merge approved PRs with the ready-to-merge label
      conditions:
          - status-success=continuous-integration/travis-ci/pr
          - "#approved-reviews-by>=1"
          - label=ready-to-merge
      actions:
          merge:
              method: squash
              strict: smart
