apiVersion: v2
name: seed-node
description: A Helm chart for Mina Protocol's seed nodes
type: application
version: 0.1.4
appVersion: 1.16.0
dependencies:
icon: https://github.com/MinaProtocol/mina/blob/develop/frontend/website/public/static/img/coda-logo@3x.png
keywords:
- seed
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina
