version: 2
jobs:
    build:
        resource_class: large
        docker:
        - image: gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d
          auth:
            username: _json_key
            password: $JSON_GCLOUD_CREDENTIALS
        steps:
            - checkout
            - run:
                name: Lint
                command: eval `opam config env` && make check-format
            - run:
                name: Build Haskell
                command: source ~/.profile && make kademlia
            - run:
                name: Build OCaml
                command: eval `opam config env` && make build 2>&1 | tee /tmp/buildocaml.log
            - run:
                name: Count OCaml Warns
                command: ./scripts/buildwarns.py /tmp/buildocaml.log
            - run:
                name: Build deb Package
                command: make deb
            - store_artifacts:
                path: /tmp/artifacts

    build_withsnark:
        resource_class: large
        docker:
        - image: gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d
          auth:
            username: _json_key
            password: $JSON_GCLOUD_CREDENTIALS
        steps:
            - checkout
            - run:
                name: Build Haskell
                command: source ~/.profile && make kademlia
            - run:
                name: Enable snarks --  make withsnark
                command: make withsnark
            - run:
                name: Get Proving Keys -- make withkeys
                command: make withkeys
            - run:
                name: Build OCaml
                command: eval `opam config env` && make build 2>&1 | tee /tmp/buildocaml.log
            - run:
                name: Build deb Package with verification keys
                command: make deb
            - run:
                name: Build provingkeys
                command: make provingkeys
            - store_artifacts:
                path: /tmp/artifacts

    build_public:
        resource_class: large
        docker:
        - image: gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d
          auth:
            username: _json_key
            password: $JSON_GCLOUD_CREDENTIALS
        steps:
            - checkout
            - run:
                name: Build Haskell
                command: source ~/.profile && make kademlia
            - run:
                name: Enable snarks --  make withsnark
                command: make withsnark
            - run:
                name: Enable update killing
                command: make withupdates
            - run:
                name: Get Proving Keys -- make withkeys
                command: make withkeys
            - run:
                name: Build OCaml
                command: eval `opam config env` && make build 2>&1 | tee /tmp/buildocaml.log
            - run:
                name: Build deb Package with verification keys
                command: make deb
            - store_artifacts:
                path: /tmp/artifacts

    test-runtest:
        resource_class: large
        docker:
        - image: gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d
          auth:
            username: _json_key
            password: $JSON_GCLOUD_CREDENTIALS
        steps:
            - checkout
            - run:
                name: Build Haskell
                command: source ~/.profile && make kademlia
            - run:
                name: Test make test-runtest
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" make test-runtest

    test-stake:
        resource_class: large
        docker:
        - image: gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d
          auth:
            username: _json_key
            password: $JSON_GCLOUD_CREDENTIALS
        steps:
            - checkout
            - run:
                name: Build Haskell
                command: source ~/.profile && make kademlia
            - run:
                name: Test make test-stakes
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" make test-stakes

    test-sig:
        resource_class: large
        docker:
        - image: gcr.io/o1labs-192920/ocaml-base:00bd64dcf1b4d171a26bcc26775c78181c2e726d
          auth:
            username: _json_key
            password: $JSON_GCLOUD_CREDENTIALS
        steps:
            - checkout
            - run:
                name: Check .circleci Render
                command: make check-render-circleci
            - run:
                name: Build Haskell
                command: source ~/.profile && make kademlia
            - run:
                name: Build OCaml
                command: eval `opam config env` && make build 2>&1 | tee /tmp/buildocaml.log
            
            - run:
                name: full-test | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'full-test'
            - run:
                name: coda-peers-test | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-peers-test'
            - run:
                name: coda-transitive-peers-test | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-transitive-peers-test'
            - run:
                name: coda-block-production-test | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-block-production-test'
            - run:
                name: coda-shared-prefix-test -who-proposes 0 | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-shared-prefix-test -who-proposes 0'
            - run:
                name: coda-shared-prefix-test -who-proposes 1 | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-shared-prefix-test -who-proposes 1'
            - run:
                name: coda-shared-state-test | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-shared-state-test'
            - run:
                name: coda-restart-node-test | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'coda-restart-node-test'
            - run:
                name: transaction-snark-profiler -check-only | proof_of_signature
                command: source ~/.profile && PATH="$PATH:$(nix-shell . --run 'dirname $(which spirv-val)')" CODA_CONSENSUS_METHOD=proof_of_signature ./test_integration_test.sh 'transaction-snark-profiler -check-only'

workflows:
    version: 2
    coda_parallel:
        jobs:
            - build
            - build_withsnark
            - build_public
            - test-runtest
            - test-sig
            #- test-stake
    # NOTES: Save this idea for later (nightly/scheduled workflows)
    # nightly:
    #     triggers:
    #         - schedule:
    #             cron: "0 0 * * *"
    #             filters:
    #                 branches:
    #                     only: master
    #     jobs:
    #         - build_withsnark

