version: 2
jobs:
  build:
    resource_class: xlarge
    docker:
      - image: gcr.io/o1labs-192920/ocaml-base:cb142209e77e4e3f4fe05d192bdb1e85cc879d6d
        # ENV variable is located in circleci
        auth:
          username: _json_key
          password: $JSON_GCLOUD_CREDENTIALS
    steps:
      - checkout

      - run:
          name: Lint
          command: eval `opam config env` && make check-format

      - run:
          name: Build Haskell
          command: source ~/.profile && cd app/kademlia-haskell && nix-build release2.nix

      - run:
          name: Build OCaml
          command: eval `opam config env` && jbuilder build -j8

      - run:
          name: Run All Tests
          command: make test

