version: 2
jobs:
  build:
    docker:
      - image: o1labs/ci-base:latest
    steps:
      - checkout

      - setup_remote_docker

      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json

      - run: /root/google-cloud-sdk/bin/gcloud --quiet components update
      - run: /root/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: /root/google-cloud-sdk/bin/gcloud config set project o1labs-192920

      - run: /root/google-cloud-sdk/bin/gcloud docker -- pull gcr.io/o1labs-192920/ocaml-base:1bc91d4f8ae340524faacc8901638f0526127728

      - run:
          name: Nanobit docker
          command: make nanobit-docker

      - run:
          name: Testbridge docker
          command: make testbridge-docker
