version: 2
jobs:
  build:
    docker:
      - image: gcr.io/o1labs-192920/ocaml-base:fa6c1ffeb2dd09fd5e53271fa90ef96845782156
        # ENV variable is located in circleci
        auth:
          username: _json_key
          password: $JSON_GCLOUD_CREDENTIALS
    steps:
      - checkout

      # - setup_remote_docker
      - run:
          name: Build Haskell
          command: source ~/.profile && cd app/kademlia-haskell && nix-build release2.nix

      - run:
          name: Build OCaml
          command: eval `opam config env` && jbuilder build

      - run:
          name: Run All Tests
          command: eval `opam config env` && jbuilder runtest --verbose
