version: 2
jobs:
  build:
    docker:
      - image: gcr.io/o1labs-192920/ocaml-base:f1db9a46932c092deee291da8f91dbd4430398f7
        # ENV variable is located in circleci
        auth:
          username: _json_key
          password: $JSON_GCLOUD_CREDENTIALS
    steps:
      - checkout

      # - setup_remote_docker

      - run:
          name: Build All
          command: eval `opam config env` && jbuilder build

      - run:
          name: Run All Tests
          command: eval `opam config env` && jbuilder runtest --verbose
